spring.application.name=requisition-management-api

spring.datasource.url=jdbc:postgresql://localhost:5432/requisition-db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# JWT secret et expiration
jwt.secret=i4k94l192p8ha6m7v2kypexo5u80sz1k94mh5barxg101pq0dc839vi6aqilfbl1x5ah6sz5d7wn7ymt78dsia17lc9scifk95h17kvq9gtbqfvr631cvpca0q4

jwt.expiration=3600000000

spring.mail.host=localhost
spring.mail.port=9025
spring.mail.username=requisition@gmail.com
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
#
#springdoc.api-docs.enabled=true

server.port=8000
server.servlet.context-path=/api

